// <auto-generated />
using System;
using FairwayDrivingRange.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FairwayDrivingRange.Infrastructure.Migrations
{
    [DbContext(typeof(FairwayContext))]
    partial class FairwayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FairwayDrivingRange.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateBooked")
                        .HasColumnType("datetime2");

                    b.Property<int>("Lane")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FairwayDrivingRange.Domain.Entities.CustomerInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerInformation");
                });

            modelBuilder.Entity("FairwayDrivingRange.Domain.Entities.GolfClub", b =>
                {
                    b.Property<int>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerialNumber"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.HasKey("SerialNumber");

                    b.HasIndex("BookingId");

                    b.ToTable("GolfClubs");
                });

            modelBuilder.Entity("FairwayDrivingRange.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BookingPrice")
                        .HasColumnType("float");

                    b.Property<double>("ClubPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FairwayDrivingRange.Domain.Entities.Booking", b =>
                {
                    b.HasOne("FairwayDrivingRange.Domain.Entities.CustomerInformation", "Customer")
                        .WithOne("Booking")
                        .HasForeignKey("FairwayDrivingRange.Domain.Entities.Booking", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FairwayDrivingRange.Domain.Entities.GolfClub", b =>
                {
                    b.HasOne("FairwayDrivingRange.Domain.Entities.Booking", "Booking")
                        .WithMany("clubs")
                        .HasForeignKey("BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("FairwayDrivingRange.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FairwayDrivingRange.Domain.Entities.CustomerInformation", "CustomerInformation")
                        .WithOne("Transaction")
                        .HasForeignKey("FairwayDrivingRange.Domain.Entities.Transaction", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerInformation");
                });

            modelBuilder.Entity("FairwayDrivingRange.Domain.Entities.Booking", b =>
                {
                    b.Navigation("clubs");
                });

            modelBuilder.Entity("FairwayDrivingRange.Domain.Entities.CustomerInformation", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
